
# SCRAPER CONSTANTS
TEAM_NAME = "Cornell"
START_YEAR = 2015
END_YEAR = 2020
GAMES_URL = "http://www.boydsworld.com/cgi/scores.pl?"


# STATS CONSTANTS

# VISUALIZATION CONSTANTS
FIGURE_WIDTH = 800
FIGURE_HEIGHT = 600